sequence:
  input_dim: 1280
  action_dim: 1024
  lr: 0.0001
  gamma: 0.95
  buffer_size: 10000
  batch_size: 64

structure:
  input_dim: 256
  action_dim: 1024
  lr: 0.0001
  gamma: 0.95
  buffer_size: 10000
  batch_size: 64

graph:
  input_dim: 128
  action_dim: 1024
  lr: 0.0001
  gamma: 0.95
  buffer_size: 10000
  batch_size: 64

expression:
  input_dim: 128
  action_dim: 1024
  lr: 0.0001
  gamma: 0.95
  buffer_size: 10000
  batch_size: 64

proteoform:
  input_dim: 65
  action_dim: 1024
  lr: 0.0001
  gamma: 0.95
  buffer_size: 10000
  batch_size: 64
